### ISSUE TITLE
Feature : system filters for Mineral

### ISSUE THREAD

**Issue by kwaio** [rubybrowncoat/Aurora-Electrons#12]
Being able to restrict to quickly select populated systems only (or systems with colonies even if empty?) would be nice.
Also be able to deselect hostile alien/military-restricted systems.

**Comment by rubybrowncoat** [comment]
https://github.com/rubybrowncoat/Aurora-Electrons/releases/tag/v0.8.10

**Comment by rubybrowncoat** [comment]
Released in https://github.com/rubybrowncoat/Aurora-Electrons/releases/tag/v0.8.10
